language: node_js
node_js: stable



cache:
  directories:
    - node_modules
# S: Build Lifecycle

before_install:
  git clone https://github.com/homobulla/homo themes/next

install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update homo-blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - develop
env:
 global:
   - GH_REF: github.com/homobulla/homobulla.github.io

